---
name: Project Charter Check Template
about: Address suggestions and potential Typos in Documents
title: "[DOCS] Project Charter Check #"
labels: documentation
assignees: ''

---

### LABELS

<details>

#### Text Format
**Bold**: replaced word in original text
Normal: Citation from original text
*Italic*: Comment
#### Suggestions
IMPROVEMENT: something to add, to be defined by document owner
TYPO: a suggestion for correcting a found typo

</details>

### What has been quality checked?
#### Compliance with Use cases/Business Requirements

- [ ] Make sure it follows the client's requests.
- [ ] Make sure In Scope and Out of Scope is well set
- [ ] Make sure it is in line with the rest of the Documents

#### Readability

- [ ] Make sure paragraphs are mostly never over 3-4 lines long.
- [ ] Make sure the document features at least 1/10th visuals.
- [ ] Make sure the document features some admonition for information hierarchy.
- [ ] Ensure accessibility by checking Links, Image alt attributes, and presence of Table of content
- [ ] Make sure the heading logic is clear (no H2 in an h3 for instance)

#### Coherence

- [ ] Make sure the document doesn't contradict itself and with the rest of the documents.

#### Spell Check

- [ ] Make sure the document is written in a professional, idiomatic American English

## Global Suggestions

*list your suggestions that apply to the whole document or its style here*

## Detailed Suggestions

*list all the specific suggestions here, most notably typos and improvements*
