name: Test Case Form
description: Declares a test case (form variant) specific to the hybrid game project.
title: "[TESTING] TEST_NAME"
labels: [test]
assignees: [mathiskakal]
projects: [algosup/45]
body:

  - type: input
    id: testcase-title
    attributes:
      label: Test Case Title
      description: A brief title of what the test is.
      placeholder: e.g., Validate Hint System Functionality
    validations:
      required: true

  - type: dropdown
    id: test-status
    attributes:
      label: Test Status
      options:
        - Pending
        - Failed
        - Blocked
        - Passed
      default: 0
    validations:
      required: true

  - type: textarea
    id: test-description
    attributes:
      label: Test Description
      description: Describe what the test will do in simple terms.
      placeholder: This test ensures the hint system provides progressive hints without skipping essential learning content.
    validations:
      required: true

  - type: dropdown
    id: test-execution
    attributes:
      label: Test Execution
      description: Specify if it is to be run automatically or manually.
      options:
        - Automatic
        - Manual
        - Both

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: Describe why the test is relevant.
      placeholder: To ensure the hint system is functional, aligned with educational goals, and user-friendly.
    validations:
      required: true

  - type: dropdown
    id: test-environment
    attributes:
      label: Test Environment
      description: Pick the predefined environment from which the test should be run from.
      options:
        - Android Device (5.0+)
        - iOS Device (14+)
        - QA PC (Windows 11 - Lenovo)
        - QA MacBook Air (MacOS)
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Describe the elements the test(s) depend on.
      placeholder: GODOT 4.3 runtime, physical cards with alphanumeric codes, stable network connection...
    validations:
      required: true

  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: Any requirements or conditions that must be met before performing the test.
      placeholder: The app must be installed on the target device, physical cards are available, backend services are active, etc.
    validations:
      required: true

  - type: textarea
    id: post-conditions
    attributes:
      label: Post-conditions
      description: Describe the expected state of the system after the test was executed, regardless of whether it failed or passed.
      placeholder: The system should return to its normal state, and all test data should be logged for review...
    validations:
      required: true

  - type: textarea
    id: test-data
    attributes:
      label: Test Data
      description: Describe the data required as an input for the test.
      placeholder: Hint system test data, sample puzzles, alphanumeric codes from physical cards...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps
      description: "You may use the markdown table template below to lay out the different steps of the test."
      placeholder: "1. Launch the app\n2. Access the puzzle screen\n3. Input valid code from card\n4. Activate hint system..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <details><summary><ins><em>Click to show template</em></ins></summary><br>
        
        \| Step ID \| Step Description \| Step Date \| Expected Results \| Actual Results \| Pass / Fail \| Add. Notes\|
        \|--------\|--------\|--------\|--------\|--------\|--------\|--------\|
        \| O \| Cell \| Cell \| Cell \| Cell \| Cell \| Cell \|
        \| 1 \| Cell \| Cell \| Cell \| Cell \| Cell \| Cell \|
        \| 2 \| Cell \| Cell \| Cell \| Cell \| Cell \| Cell \|
        
        </details>

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional comments or observations.
      placeholder: Observations during the test run or potential improvements to the feature...
    validations:
      required: false
